### ISSUE TITLE
Allow display .prologue/.epilogue.html even if dotfiles are not displayed

### ISSUE THREAD

**Issue by hugo-akaora** [9001/copyparty#101]
Hello,

It appears that .prologue/.epilogue.html files are only displayed when dotfiles are ~~not~~ displayed.

Would it be possible to always display the .prologue/.epilogue.html?

It seems according to `README.md` that it should be the default behavior. Although in practice it is not the case.

Thank you

**Comment by 9001** [comment]
Nice, thanks for pointing this out! yeah the readme is correct, this should have worked. I'm pretty sure this commit is to blame: https://github.com/9001/copyparty/commit/927c3bce

hopefully I'll have some time this weekend to get this fixed and make a new release :>
