### ISSUE TITLE
up2k not work in Google Chrome

### ISSUE THREAD

**Issue by 4ragaki** [9001/copyparty#108]
**Describe the bug**
any file upload task by up2k will fail in Google Chrome 129.0.6668.100, seems to be related with filename or filesystem charset, but full alphabet filename fails too.

**To Reproduce**
no specific step

edit: it's triggered by enabling https

**Client details**
* OS version: Arch Linux
* browser version: Google Chrome 129.0.6668.100

**Additional context**
the error page:
![image](https://github.com/user-attachments/assets/83c442e7-327d-4ca3-b397-a66aab2e5c7b)

btw it works fine in Mozilla Firefox 131.0

**Comment by 9001** [comment]
ohh, i think i know what this is - could you try to switch the language to English? if that makes it work, I'll get it fixed properly tonight.

**Comment by 4ragaki** [comment]
> ohh, i think i know what this is - could you try to switch the language to English? if that makes it work, I'll get it fixed properly tonight.

I found it's related to https just now, upload works great with http.

**Comment by 9001** [comment]
> I found it's related to https just now, upload works great with http.

that's weird... could you please try to change language to Chinese, then refresh the page, and see if the problem returns?

**Comment by 4ragaki** [comment]
> > I found it's related to https just now, upload works great with http.
> 
> that's weird... could you please try to change language to Chinese, then refresh the page, and see if the problem returns?

Hi, yes after some more rounds of testing, ui language should be the problem. it works sometime after switching between languages so I made a wrong conclusion before.

**Comment by 9001** [comment]
Awesome, thanks! I plan to have it fixed tonight, unless something else comes up 👍
