### ISSUE TITLE
Upload crashes browser at "handshaking..." step

### ISSUE THREAD

**Issue by Edward205** [9001/copyparty#111]
This might be a problem with my configuration, I apologise in advance if that's the case and I'm wrongfully reporting this as a bug with copyparty itself.

**Describe the bug**
When attempting to uploading a file with up2k, it will get stuck at the "handshaking..." step. The page will be frozen, and eventually will crash. I was able to get this crash reporting page on my phone:
![image](https://github.com/user-attachments/assets/84e9bd21-7508-49cc-b65a-baf688a3c486)
(on desktop the browser only shows the "tab crashed" page)

I have tested this on Firefox mobile, Chromium Linux, Firefox Linux, and this behaviour is identical on all of them.

**To Reproduce**
Upload any file, of any size.

**Server details**
* server OS / version: Fedora Server 40
* python version: 3.12.6
* copyparty arguments: 
```  
  p: 3938  
  e2dsa  
  e2ts   
  z
  xff-src: lan
  shr: /share
  name: maisha
  u2sz: 96
  ftp: 3921
```
* filesystem: xfs

**Client details**
Issue occurs on:
* Linux desktop with Firefox 131.0.3
* Linux desktop with Chromium 129.0.6668.100
* Android phone with Firefox 113

**Additional context**
The issue occurs even on a local network, over HTTP. The server is usually behind a cloudflare proxy with HTTPS, and the issue occurs there too. The simple uploader works fine. The copyparty server is behind an nginx proxy using the [recommended configuration](https://github.com/9001/copyparty/blob/hovudstraum/contrib/nginx/copyparty.conf) with cpp_tcp.
Server logs:
```
20:03:10.688 192.168.0.199 51284   GET  /test/?tree= @edward
20:03:10.688 192.168.0.199 51268   GET  /test/?ls @edward
20:03:30.711 192.168.0.199 51268   POST /test/ @edward
20:03:30.712 192.168.0.199 51268   POST len=9919 type=utf-8 ip=192.168.0.199 user=edward req='/test/' json={'name': 'RimWorld1-5-4241Linux.tar.gz', 'size': 219002129, 'lmod': 1728414597.881, 'life': 0, 'hash': '209 chunks'}
20:03:30.713 fstab                 inspecting mtab for changes
20:03:30.720 fstab                 mtab has changed; reevaluating support for sparse files
20:03:30.720 fstab                 found xfs at home/copyparty/files_test/test
20:03:30.721 up2k                  sparse files ok on xfs filesystem at /home/copyparty/files_test/test
20:03:30.721 192.168.0.199 51268   {"name": "RimWorld1-5-4241Linux.tar.gz", "purl": "/test/", "size": 219002129, "lmod": 1728414597, "sprs": true, "hash": ["X7izbzqaxcEGzRyRIbqIgtvxBBMvtYZOBHw_stVdDfIu", "cgs2Ybk3Z5Sm82tTdyGUlHlqjY0g7fbVwj9CqM4nHGFz", ...
```

**Comment by 9001** [comment]
wow, yeah your hunch was right -- luckily this is config related.

the u2sz option expects a tuple of integers, for example `16,32,64` which sets the lower and upper boundaries of allowed values in the UI to between 16 and 64, and the default to be 32.

in hindsight, if someone specifies just one value (96), it should be smart enough to understand you meant `1,96,96` instead of, well, exploding uncontrollably as it does now.

thanks for bringing this up!

**Comment by Edward205** [comment]
I changed the configuration to: 
```
u2sz: 1,96,96
```
and now it works great! Thanks for the help, and I'm glad I was able to fix a small issue!
