### ISSUE TITLE
Copy and paste instead of cut and paste

### ISSUE THREAD

**Issue by vorpalhex** [9001/copyparty#115]
I'd like users to be able to copy files from a big unsorted droppile of a directory into their user directories by copying (not cut + paste) files over. As far as I can tell this isn't implemented yet without downloading and re-upping?

**Comment by 9001** [comment]
yup; currently copy/paste is not implemented, only cut/paste. I recall thinking copy would be too tricky to get right, mainly due to symlinks and recursing into subvolumes... But you're not the first person to ask, so I'll take another look.

**Comment by 9001** [comment]
I think this and #114 should be fine now, so here's a beta which includes both: [COPYparty.zip](https://github.com/user-attachments/files/17669817/COPYparty.zip)

would be awesome if you get a chance to test it a bit :>

I'm tempted to take a shot at another big feature before the next release, so v1.16.0 will probably be either this sunday or next depending on how that goes.

**Comment by 9001** [comment]
#46 mentioned some usecases where it'd be real handy with a UI for fixing filename conflicts, sooo... [COPYparty2.zip](https://github.com/user-attachments/files/17671725/COPYparty2.zip)

**Comment by vorpalhex** [comment]
Is it possible to get a docker image for testing?

**Comment by 9001** [comment]
absolutely - in fact, it got included in the latest release, so it's just a quick update away :>

**Comment by vorpalhex** [comment]
My quick testing everything looks good so far. I got one weird dialog with an "undefined" when trying to paste during a reindex (it did succeed once the reindex was done) but everything else appears fine. Will let my users at it for a few days and see if they discover any new features. 


![image(1)](https://github.com/user-attachments/assets/c33cab11-79c3-430b-98dc-ba5c4f74b535)

Thanks again!
