### ISSUE TITLE
list index out of range with html permission when accessing file other than index.html (only on root path)

### ISSUE THREAD

**Issue by hugo-akaora** [9001/copyparty#121]
Hello @9001, hope you're okay?

**Describe the bug**
I got error "list index out of range" with html permission only on root path when I try to access other file than `index.html`. If the file is in a sub path/folder, it works correctly.

**To Reproduce**

- Create index.html with some content
- Create toto.html with some content
- Create folder/toto.html with some content.
- Configure directory with `h` (html) permission.
- Try to access toto.html
- Try to access folder/toto.html

**Expected behavior**
I expect that all folders/paths should be served the same.

Actually my use case is to include some scripts/css/other files directly in my index.html. Right now I must put included files in subpath.

**Server details**
if the issue is possibly on the server-side, then mention some of the following:
* server OS / version: 1.16.2
* docker

**Comment by 9001** [comment]
Thanks! you're right, this should behave the way you expect.

I'm just waiting for the new python version to be released, and according to the schedule that should be either today or tomorrow... so the fix is right around the corner :>
