### ISSUE TITLE
Combine IDP and regular login?

### ISSUE THREAD

**Issue by nanawel** [9001/copyparty#122]
I'm trying to configure Authentik so that people can use their exiting IDP session on it to access copyparty directly.

My problem is that as soon as I declare (as documented [here](https://github.com/9001/copyparty/blob/hovudstraum/docs/examples/docker/idp-authentik-traefik/cpp/copyparty.conf#L26-L27))

```
[global]
  ...
  idp-h-usr: x-idp-user
  idp-h-grp: x-idp-group
```

I lose the ability to use the regular login method with a cookie.
When I enter my password, I get the "hi {user}" page, but then I m' redirected to the default page again, and in the header I can see I'm not logged in.

Is it expected? Is there a way to combine both methods? (as a fallback, or if a user is only defined in copyparty for example)

Thanks again for your software, it kicks ass ^^

_EDIT: After reading the source code I've tried adding `bauth-last` to the configuration but no luck :(_

**Comment by 9001** [comment]
hey! and thanks :grin: 

until now, the IdP auth would entirely disable the regular login stuff, since that's what the other IdP usecases appeared to expect.  

but now that you ask, I agree it would be cool to be able to mix the two -- so now it does this:

* first, check if there's a password or login-session which matches any of the users defined in the copyparty config / commandline args
* then, it checks if there's an IdP username header, and if that header has a value, and if that header is trusted (from a legit reverseproxy) -- if all of those is true, then the IdP username wins

here's a beta -- [copyparty-sfx.py.zip](https://github.com/user-attachments/files/18053297/copyparty-sfx.py.zip) -- would it better with a docker image instead? In that case, which image flavor and archtecture are you running on?

**Comment by nanawel** [comment]
Hey thanks a lot!
Yes I'm using the Docker image, the `ac` variant on `amd64`.

**Comment by 9001** [comment]
Alright -- you should get the beta if you switch to the `beta` tag, so  `copyparty/ac:beta` :+1: 

just please make sure to switch back to `copyparty/ac:latest` when the next version is released, since the beta tag doesn't get regular updates!

let me know if you hit any issues :>

**Comment by nanawel** [comment]
I can confirm that the regular login now still works when enabling IDP support! \o/

I still have to figure out the proper way to trigger the IDP-based auth using a special URL, but that's a problem on my side. I'll post the configuration for Apache using mod_auth_openidc if I find one that's working.

Thanks, again :+1:

**Comment by nanawel** [comment]
It finally works the way I wanted. I'll try to sum up the necessary configurations on copyparty and Apache's sides.

In copyparty (using the current beta, but soon the next stable I'm sure):

```
[global]
  name: copyparty.example.org
  # OpenID/Authentik
  idp-h-usr: x-Authentik-User
  idp-h-key: X-Authentik-SOMESECRET
  bauth-last
```

Now in Apache, assuming that

- your Authentik is running on `authentik.example.org`
- your copyparty's public address is `copyparty.example.org`
- your copyparty is reachable at `copyparty:3923` from Apache
- you've created an **OAuth2/OIDC** application and provider on Authentik with the slug `copyparty`
- you've set the **Launch URL** for copyparty in Authentik to https://copyparty.example.org/oauth/authorize (this is perfectly arbitrary, see the `<Location>` section below)
- the client ID is `YOURCLIENTID`
- the client secret is `YOURCLIENTSECRET`
- the secret passphrase is `YOURSECUREPASSPHRASE`
- the secret header for securing the OIDC headers is `X-Authentik-SOMESECRET`
- you want Authentik's `nickname` field to be used as the username in copyparty

> Only important directives are present here, you might need to add additional SSL/TLS options to handle HTTPS properly.

```apache
<VirtualHost *:443>
ServerName copyparty.example.org
DocumentRoot /var/www

# Authentik OpenID Configuration
OIDCProviderMetadataURL https://authentik.example.org/application/o/copyparty/.well-known/openid-configuration
OIDCClientID YOURCLIENTID
OIDCClientSecret YOURCLIENTSECRET
OIDCCryptoPassphrase YOURSECUREPASSPHRASE

OIDCProviderIssuer https://authentik.example.org/application/o/copyparty/
OIDCProviderAuthorizationEndpoint https://authentik.example.org/application/o/authorize/
OIDCProviderTokenEndpoint https://authentik.example.org/application/o/token/
OIDCRedirectURI https://copyparty.example.org/redirect_uri
OIDCScope "openid email profile"

<Location "/oauth/authorize">
  AuthType openid-connect
  Require valid-user

  RewriteEngine On
  RewriteRule .* / [R=301,L]
</Location>

<Proxy *>
  Deny from all

  AuthType openid-connect
  Require valid-user
  OIDCUnAuthAction pass

  RequestHeader set X-Authentik-User "%{OIDC_CLAIM_nickname}e" env=OIDC_CLAIM_sub
  RequestHeader set X-Authentik-SOMESECRET OK env=OIDC_CLAIM_sub

  Satisfy any
</Proxy>

ProxyPass        /oauth/authorize !

ProxyPass        /                http://copyparty:3923/ nocanon
ProxyPassReverse /                http://copyparty:3923/

ProxyPreserveHost On
AllowEncodedSlashes On
</VirtualHost>
```

Now you can access your copyparty and log in using the regular credentials as usual, assuming you have local accounts on it, but you can also trigger the OIDC authentication flow by hitting `https://copyparty.example.org/oauth/authorize` which will redirect you to the login page in Authentik (or, if you're already logged in, to your copyparty's home page with a valid session).

Enjoy!

**Comment by jameskr97** [comment]
I'm glad this implementation is supported. This is usually referred to as a "forward-auth" method to having an external iDP. Though, it does require that the server is behind a reverse-proxy. Which for home use is likely to be expected.

Though, I'm curious, would this project be open to PR's that actually implement oauth within copyparty, so a reverse proxy wouldn't be necessary?

I'd be interested in contributing this if maintainers are open to it.

**Comment by sithtoast** [comment]
@nanawel do you know how this config would work with nginx NPM?

**Comment by nanawel** [comment]
> [@nanawel](https://github.com/nanawel) do you know how this config would work with nginx NPM?

Unfortunately no, I'm not skilled enough to convert it, especially because of the env variables usage in Apache that can't be reproduced the same way in Nginx. 😕 

But as a good starting point, you might want to take a look at the [official documentation](https://docs.goauthentik.io/docs/add-secure-apps/providers/proxy/server_nginx).
