### ISSUE TITLE
[Help] Does copyparty support suburls?

### ISSUE THREAD

**Issue by JeremyStarTM** [9001/copyparty#13]
I want to use copyparty as a simple file sharing service on my own server. And because I don't use domains (using NoIP currently :P) I wanted to ask if copyparty supports suburls? I've implemented a Apache² reverse proxy setup and it does not work correctly (as seen in the screenshot below). Can I somehow fix it (by implementing it manually or changing something in the args/config)?

A screenshot displaying a broken copyparty installation with DevTools network monitoring enabled:
![broken copyparty screenshot](https://user-images.githubusercontent.com/53786253/206871165-05c17b71-f079-4d42-8f9d-36148e0d62db.png)

**Comment by 9001** [comment]
Hey! and thanks for giving copyparty a go :+1: 

You guessed it, that wasn't supported yet -- but it's time to fix that. Next version will have a new argument `--webroot` where you can provide the suburl you've placed copyparty at.

Please [grab the beta](https://ocv.me/stuff/copyparty-sfx.py) if you'd like, and let me know if it explodes :>

...on second thought, "webroot" probably isn't the best name for that -- maybe `--rp-loc` would be better

**Comment by JeremyStarTM** [comment]
Thank you for the fast response :)
I'll try the beta and respond if it works or exploded.

**Comment by JeremyStarTM** [comment]
Thank you! It worked first try.
But, copyparty seems to ignore the --webroot argument sometimes and the console throws this error every time I visit copyparty:
`incorrect --webroot or webserver config; expected vpath starting with [share] but got []`

Anyway, I can upload files now, so thank you anyway!

**Comment by 9001** [comment]
Nice! Glad to hear it mostly worked. But I'd like to figure out what's going on with the URL rewriting, especially if it turns out to be a bug on my end :>

copyparty will only print that message if it gets the `x-forwarded-for` header, which is added by apache on the way in, so I believe all the requests are coming through apache like they should. Did you perhaps do some URL rewriting in the apache config with mod_rewrite or similar? If yes, please try to disable those.

If that doesn't help, did you notice any pattern in which requests are being rejected? Maybe it'll become more obvious by enabling `--ihead=*` to see all incoming headers.

**Comment by JeremyStarTM** [comment]
I don't actually have any rewring enabled for /share/ (where copyparty lives), only for old paths like /sync/ that redirect to /syncthing/ on my server, so that should not be a problem. I may try enabling `--ihead=*` later because I currently don't have time for that. Still thank you. If I have any more information regarding this, I'll update you here.

**Comment by 9001** [comment]
no worries! I'll try an apache setup too, only ever tested with nginx so far :+1:

**Comment by 9001** [comment]
okay, think I got it -- apache strips away the location from the request url, so you have to include it in the ProxyPass command, making it `ProxyPass "/stuff" "http://127.0.0.1:3923/stuff"` for example :>

**Comment by JeremyStarTM** [comment]
I've been very busy because of school in the last days, so thank you very much for testing that for me :wink: 

What I almost forgot to tell you: I'm now hosting copyparty publicly on my server (for my open source organization) and I made sure to credit you (as seen in the screenshot below). Hope this project continues and maybe I'll even contribute myself (although I'm not a python or HTML/JS developer).

![credit on fs.staropensource.de](https://github.com/user-attachments/assets/c1a7e0e1-683a-4eda-878e-177fc4a8d31f)

**Comment by hugo-akaora** [comment]
Hello,
Did you merge the improvement?
Can't find `webroot` argument in `docker run --rm -it copyparty/ac --help`.
Thank you!

**Comment by 9001** [comment]
Hey,

`--webroot` was renamed to `--rp-loc` before the release was made, sorry for the confusion :>

Let me know if you hit any issues with it!
