### ISSUE TITLE
Cannot connect to ftps server: type object 'FtpHandler' has no attribute 'hub'.

### ISSUE THREAD

**Issue by Gremious** [9001/copyparty#30]
Heya, I cannot connect to the s(?)ftp server, with the following error in the server:

```
16:20:08.170 pyftpdlib             Traceback (most recent call last):
  File "/tmp/pe-copyparty.1000.5404.0/ftp/pyftpdlib/servers.py", line 175, in handle_accepted
    handler = self.handler(sock, self, ioloop=self.ioloop)
  File "/tmp/pe-copyparty.1000.5404.0/copyparty/ftpd.py", line 390, in __init__
    self.hub  = FtpHandler.hub
AttributeError: type object 'FtpHandler' has no attribute 'hub'
```

I have an android phone, trying to add the FTP server through the default file browser:

![image](https://github.com/9001/copyparty/assets/21365711/6e228632-9627-4d76-9e61-333b9ac27ed6)

That server message pops up every time I try to press "Add". Phone doesn't complain about being unable to reach the server, like it would if I had put in a wrong port. So I believe it's something to do with copyparty/the ftp library.

My config contains the following:

```
ftps: 3990
ftp-pr: 12000-13000
```

I have opened all of those ports as well.

I'm using Python 3.9.2 on Debian 11.

**Comment by 9001** [comment]
Thanks! Hah, turns out I've never tested `--ftps` without also having `--ftp` enabled... :sweat_smile: 

If you're eager to try it out, there's a beta at https://ocv.me/copyparty-sfx.py which includes this fix and #31 :>
