### ISSUE TITLE
Add cli/config argument to enable grid view by default

### ISSUE THREAD

**Issue by Gremious** [9001/copyparty#31]
"I'm _always_ frustrated when" I send my media folder to my friends and have to tell them they can enable grid view to actually see the images. Also, when connecting to a new device, I personally want grid mode on by default always anyway.

I scoured the help page, but I didn't find a setting for it. Did I miss it? If not, please consider adding a `--grid` or some such, thanks!

**Comment by 9001** [comment]
Good call! Yep that needs to be an option, will be added to the next ver :>
