### ISSUE TITLE
readme states Python 2 and 3 supported - errors with Python 2.7.17 and Python 3.6.9

### ISSUE THREAD

**Issue by clach04** [9001/copyparty#32]
**Describe the bug**

Either docs are wrong or code is wrong:

https://github.com/9001/copyparty/blob/9c28ba417ef05edddf4d2c88d1ae877837bdeb1f/README.md?plain=1#L5

Doc claim Python 2 and 3 support. Setup.py only mentions 3, but mentions 3.3-3.12

Copyparty fails with:

* Python 2.7.17
* Python 3.6.9
* Python 3.8.10

Does work with later version of Python, 3.11

**To Reproduce**

Checkout code, assume dependencies installed (e.g. bare minimum jinja), start server using:

    python -m copyparty

from checkout directory.

Works fine for 3.11, fails with bad syntax for others. Possibly annotation / type hint related (Python 3.7 feature?)

## Python 2
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "copyparty/__init__.py", line 19
    unicode: Callable[[Any], str] = str
           ^
SyntaxError: invalid syntax

## Python3

Type error on type hints

    Traceback (most recent call last):
      File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/home/clach04/code/py/copyparty/copyparty/__main__.py", line 28, in <module>
        from .authsrv import expand_config_file, re_vol, split_cfg_ln, upgrade_cfg_fmt
      File "/home/clach04/code/py/copyparty/copyparty/authsrv.py", line 16, in <module>
        from .bos import bos
      File "/home/clach04/code/py/copyparty/copyparty/bos/bos.py", line 6, in <module>
        from ..util import SYMTIME, fsdec, fsenc
      File "/home/clach04/code/py/copyparty/copyparty/util.py", line 36, in <module>
        from .stolen import surrogateescape
      File "/home/clach04/code/py/copyparty/copyparty/stolen/surrogateescape.py", line 35, in <module>
        def surrogateescape_handler(exc: Any) -> tuple[str, int]:
    TypeError: 'type' object is not subscriptable

**Expected behavior**

Out of box doc instructions to allow start up.

Either doc needs update or type hints should be removed. For Python 

**Screenshots**

NA

**Server details**

* server OS / version: any platform
* python version: 2.x 3.x - see above for details
* copyparty arguments: none, default
* filesystem (`lsblk -f` on linux): Any

**Client details**

NA

**Additional context**

Maybe doc last supported release for python version in docs? E.g. copyparty release ABC is the last release for Python 2.7, copyparty release XYZ is the last release for Python 3.3

NOTE copyparty-sfx.py download does work with older versions, this is specific to code checkout.

**Comment by clach04** [comment]
@9001 thanks for making this and the Android app available. I've done a few experiments with this for easily getting sharing files from my phone to PC :-) So far working better than a share to ftp tool I was using.

**Comment by 9001** [comment]
Thanks for pointing this out! You're right, there's an important detail missing from the documentation -- it's true that the module does not run as-is on older pythons, but [copyparty-sfx.py](https://github.com/9001/copyparty/releases/latest/download/copyparty-sfx.py) does, and the pypi wheel <i>almost</i> does, since they go through a build step which strips away the type hints. So that absolutely needs to be pointed out :>

But regarding that <i>"almost"</i> -- I just noticed that the pypi package fails on older py3 versions... Looks like pip decides to use a version of jinja2 which has type hints, oh dear. I'll see if it's possible to get around that with conditional version constraints or something like that :+1: 

And glad to hear the app still behaves :-)

**Comment by clach04** [comment]
Thanks for the quick response. I just figured out there are over 700 hints so I was suspecting the hints where deliberate :-)

    :~/code/py/copyparty$ grep -R -- '->'  copyparty/ |wc -l
    740

I found the hint in setup.py to the scripts directory. Any hints for a "build"? I tried scripts/make-sfx.sh and got errors regarding strip_hints (worth a new issue?):

    .....
    ../build/python-magic-0.4.27.tar.gz   100%[=========================================================================>]  14.33K  --.-KB/s    in 0.007s  

    2023-06-03 17:06:09 (2.08 MB/s) - '../build/python-magic-0.4.27.tar.gz' saved [14677/14677]

    collecting source ... 
    Traceback (most recent call last):
      File "../../scripts/strip_hints/a.py", line 6, in <module>
        from strip_hints import strip_file_to_string
    ModuleNotFoundError: No module named 'strip_hints'

With the working python 3.11 machine (that works) I had issues with marked.js missing (but that was a Windows machine so I don't have a good way to run the shell script).

RE conditional constraints, an old style requirements.txt file can do that (I'm no really up-to-date on the pyproject.toml system). I'd like to help if I can but there are lots of dependencies at play here I'm not familiar with.

**Comment by clach04** [comment]
I can confirm that:

    wget https://github.com/9001/copyparty/releases/latest/download/copyparty-sfx.py
    python2 copyparty-sfx.py 
    python3 copyparty-sfx.py 

does result in both Python versions starting (not tested the server) :-)

But then it's not possible to review/edit/hack on it due to the embedded binary file.

Have a great weekend! :-)

**Comment by 9001** [comment]
You're catching a lot of stuff I hadn't, nice :>

I've done some improvements on the error messages which appear when things aren't as expected -- for example, if you try to run from source or build an sfx without the webdeps available, it'll correctly point you to [devnotes/#building](https://github.com/9001/copyparty/blob/hovudstraum/docs/devnotes.md#building) which was barely visible before.

And apprently i've had `strip_hints` installed globally since forever, so I've fixed `make-sfx.sh` to grab that when necessary :+1: 

EDIT: if you're building an sfx just to test it with an older python, then `./scripts/make-sfx.sh fast` will reduce the css/js compression time substantially

As for testing out quick hacks to the code, I've found myself occasionally editing the files that are extracted into `/tmp/pe-copyparty.1000/` and restarting the sfx afterwards -- the sfx will only reextract itself if the /tmp/ files originate from another version of the sfx, and will otherwise reuse the previous files :>

(technically you could persist the edits into a new sfx by running `./scripts/make-sfx.sh re` but that would probably get real messy real fast...)

And finally, regarding the jinja2 pypi thing, I tried to install the pypi package using python 3.6 and that worked just fine... so I'll assume the issue I ran into was due to something funky with the python 3.4 environment i set up to test with. And pip is really supposed to figure this out on its own after all ;-) But, just in case, I've improved the errormessage which would appear at runtime if this were to ever happen again for some reason.

Please let me know if you run into anything else, or have any other great ideas! And a great rest of the weekend to you too :>

**Comment by clach04** [comment]
Did a few test with latest code from today:

commit df5d309d6e0507ea96027bee17d0c50245c11d75 (HEAD -> hovudstraum, origin/hovudstraum, origin/HEAD)
Date:   Sun Jun 4 14:13:35 2023 +0000

    document the make-sfx.sh `fast` option

Seeing the new expected errors, to that's working better now :-)

    localhost:~/code/py/copyparty$ scripts/make-sfx.sh

    collecting source ... 
    unhinting.........................................................k

    could not find webdeps; please see https://github.com/9001/copyparty/blob/hovudstraum/docs/devnotes.md#building
    or run with argument "ign-wd" if this was intentional

Similar for running raw code from Py2:

    localhost:~/code/py/copyparty$ python2 --version
    Python 2.7.17
    localhost:~/code/py/copyparty$ python2 -m copyparty
    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
        mod_name, _Error)
      File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
        __import__(mod_name)  # Do not catch exceptions initializing package
      File "copyparty/__init__.py", line 9
        _: int = 1  # --->--->--->  hey there! if you are reading this, your python is too old to run copyparty without some help. Please use https://github.com/9001/copyparty/releases/latest/download/copyparty-sfx.py or the pypi package instead, or see https://github.com/9001/copyparty/blob/hovudstraum/docs/devnotes.md#building if you want to build it yourself :-)
         ^

But with Python 3 still getting TypeError (which I think is really a Syntax Error in disguise, I've only tested with one version of py3 though:

    localhost:~/code/py/copyparty$ python3 --version
    Python 3.6.9
    localhost:~/code/py/copyparty$ python3 -m copyparty
    Traceback (most recent call last):
      File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/home/clach04/code/py/copyparty/copyparty/__main__.py", line 28, in <module>
        from .authsrv import expand_config_file, re_vol, split_cfg_ln, upgrade_cfg_fmt
      File "/home/clach04/code/py/copyparty/copyparty/authsrv.py", line 16, in <module>
        from .bos import bos
      File "/home/clach04/code/py/copyparty/copyparty/bos/bos.py", line 6, in <module>
        from ..util import SYMTIME, fsdec, fsenc
      File "/home/clach04/code/py/copyparty/copyparty/util.py", line 36, in <module>
        from .stolen import surrogateescape
      File "/home/clach04/code/py/copyparty/copyparty/stolen/surrogateescape.py", line 35, in <module>
        def surrogateescape_handler(exc: Any) -> tuple[str, int]:
    TypeError: 'type' object is not subscriptable

Is this one expected, I'm assuming this error is unexpected (I was expecting a similar error comment to the py2 failure).

**Comment by clach04** [comment]
@9001 I may have to take back the build error is expected. I'm getting:

    collecting source ... 
    unhinting.........................................................k

    could not find webdeps; please see https://github.com/9001/copyparty/blob/hovudstraum/docs/devnotes.md#building
    or run with argument "ign-wd" if this was intentional

for `scripts/make-sfx.sh` and `scripts/make-sfx.sh fast` 

It's failing on missing `copyparty/web/deps/mini-fa.woff`, I can't see any doc refs for the font requirements.


Extract of -x run in case it is useful:

    .. cut here
    unhinting.........................................................k
    + rm uh
    ++ realpath copyparty/res/COPYING.txt
    + licfile=/home/clach04/code/py/copyparty/sfx/copyparty/res/COPYING.txt
    + cd ../scripts
    + ./genlic.sh /home/clach04/code/py/copyparty/sfx/copyparty/res/COPYING.txt
    + '[' -e copyparty/web/deps/mini-fa.woff ']'
    + '[' ']'
    + cat

    could not find webdeps; please see https://github.com/9001/copyparty/blob/hovudstraum/docs/devnotes.md#building
    or run with argument "ign-wd" if this was intentional
    + exit 1

I can build an sfx file if ign-wd is supplied, and server starts but then dumps out:

    warning: could not find webdeps;
      if you are running the sfx, or exe, or pypi package, or docker image,
      then this is a bug! Please let me know so I can fix it, thanks :-)
      https://github.com/9001/copyparty/issues/new?labels=bug&template=bug_report.md

      however, if you are a dev, or running copyparty from source, and you want
      full client functionality, you will need to build or obtain the webdeps:
      https://github.com/9001/copyparty/blob/hovudstraum/docs/devnotes.md#building

Is down to this?:

https://github.com/9001/copyparty/blob/hovudstraum/docs/devnotes.md?plain=1#L219

> you need python 3.9 or newer due to type hints

I'm using an older version where I was testing.

Maybe add a version check to the build script? Something as simple as version_check.py with:

    import sys
    min_py_version = (3, 9)
    if sys.version_info < min_py_version:
        print('Need minimum python version %r see https://github.com/9001/copyparty/blob/hovudstraum/docs/devnotes.md#building' % (min_py_version,))
        sys.exit(1)

Which could be called after `pybin` is set in scripts/make-sfx.sh

**Comment by 9001** [comment]
> `TypeError: 'type' object is not subscriptable`

Oh whoops... yep, forgot that there are other hints in there which require even more recent python versions. Should be good now, thanks a lot :>

> It's failing on missing copyparty/web/deps/mini-fa.woff, I can't see any doc refs for the font requirements.

It's not specifically failing on the font per se -- rather it's a smoketest to check if the contents of the deps folder appears to be correct or not, without explicitly checking for each of the file that's expected in there.

What it's actually complaining about is that it needs all of the webdeps, which can either be built from source or extracted from a previous release. But, come to think of it, it would make much more sense if the script just went ahead and fixed it automatically ;-)

Give the latest commit a whirl, see if it runs any better now? :-)

**Comment by clach04** [comment]
Much better! I'm still (foolishly) using a machine that has does not have access to newer Python versions (more common than you might think, especially with SBC boards). But Python 3.6.9 is working great with the new Help option A - i.e. dl-wd to grap pre-builts.

I'm seeing two more errors, however I think it could be argued that's a new issue and out of scope of the Python version. Errors  related to awk and grep errors:


    localhost:~/code/py/copyparty$ scripts/make-sfx.sh fast dl-wd

    collecting source ... 
    unhinting.........................................................k
    git ver: 1.7.2-11-g2acdf68
    git  dt: 2023, 6, 5
    cleanup
    uncommenting.........................................................................................................k
    awk: line 2: function gensub never defined
    0 alts += 1
    gzip #2
    .................
    gen tarlist
    grep: /tmp/cpp-mksfx/h: No such file or directory
    creating tar
    compressing tar
    renamed 't.6.bz2' -> 'tar.bz2'
    creating sfx

    [SFX]    this is: copyparty None
    [SFX]  packed at: 2023-06-05, 00:10:50 UTC, None
    [SFX] archive is: /home/clach04/code/py/copyparty/scripts/sfx.py
    [SFX] python bin: /usr/bin/python3
    [SFX] python ver: CPython 3.6.9 (default, Mar 10 2023, 16:46:00) 
                      [GCC 8.4.0]

    [SFX] wrote 8d59cH bytes (8f9f4H after encode)
    done:
      /home/clach04/code/py/copyparty/dist/copyparty-sfx.py

Want me to open a new ticket for that? I think this can be closed.


Errors isolated:

    awk: line 2: function gensub never defined
    grep: /tmp/cpp-mksfx/h: No such file or directory

**Comment by 9001** [comment]
> `awk: line 2: function gensub never defined`

Wow, a machine without gnu-awk! What distro is this? :-)
Luckily you're getting the error from [this line](https://github.com/9001/copyparty/blob/9f122ccd16d938786350071ca238b41a8ea8996d/scripts/make-sfx.sh#L481), which checks whether gensub is available before actually using it. So the only drawback is your sfx will have slightly suboptimal compression. I guess the error message could have been better, but I didn't really expect the safeguard to ever hit ;-)

And the other error is not actually an error, just cosmetic, so it looks like we're all good 🎉  though I'll make a note of muting that since it doesn't look very good hehe

**Comment by clach04** [comment]
All good :+1: 

Two sessions:

## working well


    localhost:~/code/py/copyparty/copyparty$ cat /etc/*elease*
    # PLEASE DO NOT EDIT THIS FILE
    BOARD=odroidxu4
    BOARD_NAME="Odroid XU4"
    BOARDFAMILY=odroidxu4
    BUILD_REPOSITORY_URL=https://github.com/armbian/build
    BUILD_REPOSITORY_COMMIT=345a18cd9-dirty
    DISTRIBUTION_CODENAME=focal
    DISTRIBUTION_STATUS=supported
    VERSION=21.08.5
    LINUXFAMILY=odroidxu4
    ARCH=arm
    IMAGE_TYPE=stable
    BOARD_TYPE=conf
    INITRD_ARCH=arm
    KERNEL_IMAGE_TYPE=Image
    IMAGE_UUID=65de127c-ecfc-4d08-b7f7-f72445f90765
    # PLEASE DO NOT EDIT THIS FILE
    BOARD=odroidxu4
    BOARD_NAME="Odroid XU4"
    BOARDFAMILY=odroidxu4
    BUILD_REPOSITORY_URL=https://github.com/armbian/build
    BUILD_REPOSITORY_COMMIT=d3386b548-dirty
    DISTRIBUTION_CODENAME=focal
    DISTRIBUTION_STATUS=supported
    VERSION=21.08.6
    LINUXFAMILY=odroidxu4
    ARCH=arm
    IMAGE_TYPE=stable
    BOARD_TYPE=conf
    INITRD_ARCH=arm
    KERNEL_IMAGE_TYPE=Image
    BRANCH=current
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=20.04
    DISTRIB_CODENAME=focal
    DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
    NAME="Ubuntu"
    VERSION="20.04.3 LTS (Focal Fossa)"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Armbian 21.08.6 Focal"
    VERSION_ID="20.04"
    HOME_URL="https://www.ubuntu.com/"
    SUPPORT_URL="https://help.ubuntu.com/"
    BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
    PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
    VERSION_CODENAME=focal
    UBUNTU_CODENAME=focal

    localhost:~/code/py/copyparty/copyparty$ scripts/make-sfx.sh fast dl-wd

    collecting source ... 
    unhinting.........................................................k
    git ver: 1.7.2-13-g93a723d
    git  dt: 2023, 6, 6
    cleanup
    uncommenting.........................................................................................................k
    entabbening
    1 alts += 1
    gzip #8
    .................
    gen tarlist
    creating tar
    compressing tar
    renamed 't.6.bz2' -> 'tar.bz2'
    creating sfx

    [SFX]    this is: copyparty None
    [SFX]  packed at: 2023-06-07, 03:18:55 UTC, None
    [SFX] archive is: /home/pi/code/py/copyparty/copyparty/scripts/sfx.py
    [SFX] python bin: /usr/bin/python3
    [SFX] python ver: CPython 3.8.10 (default, Mar 15 2022, 12:22:08) 
                      [GCC 9.4.0]

    [SFX] wrote 8d0caH bytes (8f508H after encode)
    done:
      /home/pi/code/py/copyparty/copyparty/dist/copyparty-sfx.py

## awk error, due to missing gawk

Old Lubuntu with `mawk`

    localhost:~$ cat /etc/*elease*
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=18.04
    DISTRIB_CODENAME=bionic
    DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
    NAME="Ubuntu"
    VERSION="18.04.6 LTS (Bionic Beaver)"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 18.04.6 LTS"
    VERSION_ID="18.04"
    HOME_URL="https://www.ubuntu.com/"
    SUPPORT_URL="https://help.ubuntu.com/"
    BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
    PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
    VERSION_CODENAME=bionic
    UBUNTU_CODENAME=bionic

    localhost:~/code/py/copyparty$ scripts/make-sfx.sh fast dl-wd

    collecting source ... 
    unhinting.........................................................k
    git ver: 1.7.2-11-g2acdf68
    git  dt: 2023, 6, 5
    cleanup
    uncommenting.........................................................................................................k
    awk: line 2: function gensub never defined
    0 alts += 1
    gzip #2
    .................
    gen tarlist
    grep: /tmp/cpp-mksfx/h: No such file or directory
    creating tar
    compressing tar
    renamed 't.6.bz2' -> 'tar.bz2'
    creating sfx

    [SFX]    this is: copyparty None
    [SFX]  packed at: 2023-06-07, 03:19:15 UTC, None
    [SFX] archive is: /home/clach04/code/py/copyparty/scripts/sfx.py
    [SFX] python bin: /usr/bin/python3
    [SFX] python ver: CPython 3.6.9 (default, Mar 10 2023, 16:46:00) 
                      [GCC 8.4.0]

    [SFX] wrote 8d4dbH bytes (8f8e1H after encode)
    done:
      /home/clach04/code/py/copyparty/dist/copyparty-sfx.py
    localhost:~/code/py/copyparty$ ls -altr /usr/bin/awk /etc/alternatives/awk
    lrwxrwxrwx 1 root root 13 Mar  7  2021 /etc/alternatives/awk -> /usr/bin/mawk
    lrwxrwxrwx 1 root root 21 Mar  7  2021 /usr/bin/awk -> /etc/alternatives/awk
