### ISSUE TITLE
copyparty (help) output includes VT100 color escapes when redirected to a file

### ISSUE THREAD

**Issue by clach04** [9001/copyparty#33]
**Describe the bug**

Most tools that emit color only do so when dealing with a console/tty. Workaround is to supply `--no-ansi` flag.

**To Reproduce**

    python  dist/copyparty-sfx.py --help > help.txt

help.txt file will have binary content.

**Expected behavior**

Readable content.

**Screenshots**
NA

**Server details**

NA

**Client details**

NA

**Additional context**

NA

**Comment by clach04** [comment]
Posted https://github.com/9001/copyparty/pull/34

There is a LOT of help output, nice to be able to review at leisure in a text editor without `--no-ansi` workaround.

**Comment by 9001** [comment]
Sweet, thanks! And yep it's a sizable block of text for sure hehe
