### ISSUE TITLE
Dude you’re awesome

### ISSUE THREAD

**Issue by PixelMelt** [9001/copyparty#48]
This has to be the most over engineered project I’ve ever seen and it’s glorious.
Thanks for making it free and kudos to you for creating some great software.
I use it to host an archive of some rare music I like 😃

**Comment by 9001** [comment]
Haha thanks, you made my day :> glad to hear you're finding it useful!!

Let me know if you think of any missing features btw -- always room for more stuff if they're not too hard to add 👍

**Comment by s5lachlan** [comment]
Dude you suck
😈
