### ISSUE TITLE
browser.js error

### ISSUE THREAD

**Issue by astolfoismywaifu** [9001/copyparty#51]
**Describe the bug**
getting this:
/.cpr/browser.js @947:7
TypeError: L is undefined

**To Reproduce**
no idea, just tried visiting the base url on localhost

**Expected behavior**
i dont get this error

**Screenshots**
see below

**Server details**
if the issue is possibly on the server-side, then mention some of the following:
* server OS / version: 1.9.6

**Client details**
if the issue is possibly on the client-side, then mention some of the following:
* the device type and model: windows
* browser version: Firefox 117

**Additional context**
![error](https://github.com/9001/copyparty/assets/144506927/13d9756d-9094-4c4a-b2fc-249a103e6a8b)

**Comment by 9001** [comment]
hey, thanks for the report and for giving copyparty a go 👍

think i know how to fix it, but want to make sure I've got it right --

while the error is visible (or while visiting any site on localhost with that browser), could you open the JavaScript console (hotkey Ctrl-Shift-K), run the following two commands and copy the output?
* `localStorage.lang`
* `localStorage.lang===undefined`

also, do you happen to be running any other web stuff on this machine / do you recall ever accessing any other service on localhost?

**Comment by astolfoismywaifu** [comment]
Command 1 outputted `undefined`
Command 2 outputted `true`

Also yeah im running a media server w/ sonarr/radarr on localhost

**Comment by 9001** [comment]
huh alright, that's not what i expected so good thing we checked -- could you open up the console in the tab that's showing the error, then refresh the tab, and run the following?
```javascript
var r=['']; for (var a of 'acct dtheme lang u2sort'.split(' ')) r.push(window[a]); r.push(Object.keys(Ls)); r=r.join('], [')+']'; console.log(r);
```
there might be some relevant information being printed as the page is refreshed as well, so please include everything that appears starting from the refresh.

would also be great if you could hit Ctrl-U to show the html source of the page and copy/paste all of that into a textfile to attach here, but that would include the file listing from copyparty as well, so skip that if you've tried to view a folder that contains any filenames you wanna keep secret :>

**Comment by astolfoismywaifu** [comment]
I attached the source and only removed the name of my pc.
[copyparty.txt](https://github.com/9001/copyparty/files/12775637/copyparty.txt)
The complete console output is below.
```log-capture ok util.js:124:22
Uncaught TypeError: L is undefined
    <anonymous> http://localhost:6969/.cpr/browser.js?_=F3Dq:947
browser.js:947:7
Uncaught TypeError: treectl is undefined
    <anonymous> http://localhost:6969/.cpr/up2k.js?_=F3Dq:40
up2k.js:40:1
InstallTrigger is deprecated and will be removed in the future. localhost:6969:80:238
sha-ok util.js:124:22
TypeError: result is undefined content_script.js:131:4
Uncaught (in promise) TypeError: L is undefined
    up2k_init http://localhost:6969/.cpr/up2k.js?_=F3Dq:800
    <anonymous> http://localhost:6969/.cpr/up2k.js?_=F3Dq:26
    promise callback* http://localhost:6969/.cpr/up2k.js?_=F3Dq:25
up2k.js:800:24
GET
http://localhost:6969/favicon.ico
[HTTP/1.1 404 Not Found 0ms]

var r=['']; for (var a of 'acct dtheme lang u2sort'.split(' ')) r.push(window[a]); r.push(Object.keys(Ls)); r=r.join('], [')+']'; console.log(r);
], [astolfo], [bz b z], [en], [s], [eng,nor] util.js:124:22
undefined
```

**Comment by 9001** [comment]
Thanks! Did you by any chance run copyparty with `--lang en` or `--lang=en` ? In that case, that would be why, since it only understands `eng`  currently. I'll fix that for the next ver tho :ok_hand: :ok_hand:
