### ISSUE TITLE
Markdown placeholders

### ISSUE THREAD

**Issue by thaddeuskkr** [9001/copyparty#56]
**Describe the idea / solution you'd like**
Placeholders for markdown files, specifically `README.md` that are obtained from the server (e.g. ip address) - to be rendered and shown below the file listing (where `README.md` is usually shown) - so for example, `{request_ip_address}` will be replaced with the IP address of the user accessing the file when it is rendered.

**Additional context**
I'm aware that this idea is kinda stupid, do close if you want :)

![image](https://github.com/9001/copyparty/assets/49682825/8254d445-d05f-4ec5-93dc-a3a4692a8e14)

**Comment by 9001** [comment]
hah, awesome idea :+1:  added ^^,
