### ISSUE TITLE
Open known text filetypes in editor

### ISSUE THREAD

**Issue by Gremious** [9001/copyparty#63]
It would be nice if I could open not just `.md` files, but a few other files that are known text data wtih the editor.

Right now I have a music folder and I wanted to doublecheck an `album.nfo`, but it just opens it for download. Works good if I append `?edit` to the link manually though.

I think just accepting txt/json/config/log/yaml/nfo/etc. would be nice, lets me quickly double check a config file in the browser.

**Comment by 9001** [comment]
right, this is something that works pretty well in the list/table view, but the grid/thumbnail view doesn't get those benefits...

in the list-view, you can click the `-txt-` link next to the filename, and from there you can click `edit` to open the file in the editor. That's probably the best workaround right now.

it would make sense for the grid-view to open textfiles in the read-only viewer by default, so I'll add that when I get a chance :>

**Comment by Gremious** [comment]
Oh, good to know!

Thanks ❤️
