### ISSUE TITLE
Support .folder.jpg for folder icons too

### ISSUE THREAD

**Issue by Gremious** [9001/copyparty#67]
I just think it would be cool to be able to hide the `folder.png` image I have in like, every folder. Keeps thing cleaner :)

**Comment by 9001** [comment]
Good idea :+1:

For now, it can be done by specifying another value for `--th-covers`; it takes a list of files to look for when picking a thumbnail, the default being `folder.png,folder.jpg,cover.png,cover.jpg` -- so you'll want to change it to something like `folder.png,folder.jpg,cover.png,cover.jpg,.folder.png,.folder.jpg,.cover.png,.cover.jpg`.

A future version will do this automatically; that is, extend that list with the dotfile counterparts of each specified name to look for, but only if the database is enabled (`-e2d`). The database makes it really cheap to keep adding more names to try, but without the db it'll have to keep asking the filesystem, which quickly gets really slow.

**Comment by Gremious** [comment]
Oh, I totally missed out on `--th-covers` - thanks!

---

> A future version will do this automatically;

Awesome👍
