### ISSUE TITLE
oAuth2 Support + Public links

### ISSUE THREAD

**Issue by filliravaz** [9001/copyparty#69]
**Is your feature request related to a problem? Please describe.**
I'm looking to have a copyparty instance where upload/list files/etc... is protected via an authentication provider (Authentik in my case) but that it still allows logged-in users to create public links to allow access to specific files to unregistered/not logged-in users.

**Describe the idea / solution you'd like**
oAuth2 would obviously be great for my use case, but LDAP is also a very good option if it's easier to implement.

**Describe any alternatives you've considered**
I've considered the setup that is "suggested" in #62, but that wouldn't allow the public links, as all traffic has to go through the auth service. (Yes, I'm using Traefik and Authentik)
Maybe these two features can be implemented alongside each other?
User "creation" could be handled similarly.

**Comment by 9001** [comment]
Thanks for the input :> I believe this should come for free through #62 but it's good to keep this in mind just to be sure. Basically it would be safe to grant all users access to the copyparty instance, even if authentik gives the thumbs-down so to say, as the request would not have an associated username/group and copyparty would assume an unauthorized user. Then in the copyparty config it should be enough to enable filekeys to grant limited read-access to unauthorized users (requiring those users to have a URL with the filekey in it). But we'll have to come back to the details once I've gotten familiar with traefik and authentik 👍

**Comment by filliravaz** [comment]
I'm not super familiar with copyparty yet, but I imagine that it would work. I'd only prefer if it was possible to dynamically create public links instead of manually editing a config file.
Lastly, this is something that I didn't specify in the first message, but an addition to the public links would be a "static link" that, for example, always redirects to the latest upload in the directory. 

I ask about this because I was hoping to use copyparty in some CI/CD workflows, where I need to update files frequently but I don't realistically want to change a download URL in the workflow config.
(Sorry if I keep adding to this feature request)

**Comment by 9001** [comment]
> I'd only prefer if it was possible to dynamically create public links instead of manually editing a config file

absolutely 👍 depending on usecase you can choose between two different algorithms for generating filekeys; one would generate a new passphrase if the file is modified, and the other one only looks at the absolute filepath when choosing the key.

> a "static link" that, for example, always redirects to the latest upload in the directory

oh think I have some good news then, because that should be possible to do through the use of [handlers](https://github.com/9001/copyparty/tree/hovudstraum/bin/handlers#on404) (although a bit hacky) -- you can define custom behavior whenever someone hits a 404, which would invoke a python script that you provide instead of returning the usual 404. So for example if you link someone to folder/latest.exe, you could have a small bit of logic to return the latest exe in the folder.

still not sure if these are a perfect fit for your usecase, but it's a start at least!

**Comment by filliravaz** [comment]
> depending on usecase you can choose between two different algorithms for generating filekeys; one would generate a new passphrase if the file is modified, and the other one only looks at the absolute filepath when choosing the key.  

This should be perfect. 

> that should be possible to do through the use of [handlers](https://github.com/9001/copyparty/tree/hovudstraum/bin/handlers#on404) 

I guess it's time to get back to python programming.

However, I just realized that this
> Basically it would be safe to grant all users access to the copyparty instance, even if authentik gives the thumbs-down so to say  

While I like this approach, it may not work. In a "classic" setup authentik will intercept a connection to the service behind it, and only passes through the connection if the authentication succeeds (at least that's how my setup works right now). 
It may be solvable using some complex traefik configuration, but I'm not sure about that.

I've made a quick diagram of why I think it wouldn't work:
![Diagram](https://github.com/9001/copyparty/assets/40716956/3217e101-29b0-46ec-b602-1813737dc73c)  

However I'm also not an expert of Traefik or Authentik, so if you find a way to make it work on your end, I should be able to replicate it on mine without a lot of issues.

**Comment by 9001** [comment]
right... yeah maybe two subdomains could work, auth.site.com and guest.site.com, where only the first one is configured to go through authentik and the other one is a straight relay to copyparty? although that would require users to modify the url and replace auth with guest when sharing a link, so bit of a drawback in that sense. 

I've been a bit apprehensive about native support for oauth2 and such; at first glance they appear to be a good handful of things to understand, and hard to get right -- but maybe some of the python libraries would take care of some of that. And there's also been some interest for authenticating with Fido2/passkeys, so maybe these could be combined somehow.

**Comment by filliravaz** [comment]
oAuth2 definitely needs to be properly secured, but it looks like you already did that for username-password combinations, so it shouldn't be super difficult.

Having said that, I mainly use oAuth2 because I'd want a "safe" second factor (Fido2 key with biometrics in my case), and Authentik allows me to just log in once using the key for all (or almost all) the apps on my servers. It's both a security thing and a convenience thing.

I'll be patiently waiting for some sort of implementation, if you need a betatester, hit me up.

**Comment by gandalfb** [comment]
Hey,
copyparty looks like the tool I am looking for after fiddling with other "blown up" solutions.

I tried to cope the code but am not sure if handlers might work. Guess a http 403 handler conducting the actions below with being able to handle ENV variables (make it docker friendly)

The idea with the auth method "proxy" defining a user header seems to be very flexible.

Pseudo setting/env variable could be:
```
Auth Method = "proxy-header"   // somehow name the auth method
Auth Header = "X-Forwarded-User"  // other values are "Remote-User", ...
Auth Auto Create Users = true     // if no user exists it will be created with group below or the http403 is valid if not present
Auth Auto Create Group = User  // default access rights for those users
Auth Auto Admin User = <Content from Auth Header>  // define a user with admin rights, maybe a list
```

Maybe this can all be handled on the fly.

This way it is possible to offload auth to other components like traefik and foward auth, authelia, ...

Hope this hits the topic

**Comment by vorpalhex** [comment]
This is really an authentik configuration thing, see https://docs.goauthentik.io/docs/providers/proxy/#allowing-unauthenticated-requests

We just need share links to have a unique route (`/share` or something) that would allow public access on just that path.

**Comment by 9001** [comment]
I think this has been solved by [https://github.com/9001/copyparty#shares](shares), which makes it possible to create public links to a folder, which will appear below `/share` or another predefined location.

there is one more limitation that I've forgotten to mention in the readme, regarding [IdP volumes](https://github.com/9001/copyparty/blob/hovudstraum/docs/idp.md#idp-volumes-are-forgotten-on-shutdown) and specifically the fact that they're forgotten on shutdown. If a user creates a share by pointing into a such a volume, then the share will temporarily "disappear" after a server restart, and then start working again after the associated user makes their first request to the server.

gonna close this , but let me know if I've missed something :>

**Comment by hubidubi13** [comment]
Hi, I am currently trying to setup public shares with Authelia on version 1.20.16. Access to the actual files work, but quite a bit of javascript and css is not reachable via the single public suburl. This causes some FATAL ERROR popups. Uploading also seems to work, but I couldn't figure out how to delete a file.

Would the solution be to simply add all the needed js/css to be ignored by the IdP? Or is it possible to put the js/css behind the public share suburl too?

The files affected on a load of the public link:

- ui.css
- browser.css
- util.js
- baguettebox.js
- browser.js
- up2k.js
- favicon.ico

PS: Sorry to necro this issue, using copyparty has been very pleasant so far, thank you so much for putting in all the work!

**Comment by 9001** [comment]
> Would the solution be to simply add all the needed js/css to be ignored by the IdP?

yes; allow `/.cpr/w/`

> Or is it possible to put the js/css behind the public share suburl too?

not possible
