### ISSUE TITLE
suggestion: add a permission that grants everything

### ISSUE THREAD

**Issue by thaddeuskkr** [9001/copyparty#70]
> honestly i’m not sure about anything i’m writing in this issue… pardon me if i’m wrong and correct me :)

currently, to grant all permissions to a user in a certain directory, all permissions (e.g. rwmda) must be specified.

this makes config files look pretty messy since most people want an administrator to be able to have all those permissions in all directories.

i’m not sure if directories inherit permissions from their parents right now, but maybe it could be made such that that is done?

also, it would be nice if the admin (a) permission grants everything, but im not sure if this conflicts with anything / current configs.

or another permission could be made, maybe like o or something for owner, that grants all permissions

**Comment by 9001** [comment]
yeah good point 👍

as it sometimes makes sense to give someone `a`dmin without `w`rite/`m`ove-access (for example to see uploader IP), I'm gonna go with `A` for the new permission, which is an alias of `rwmda.` (read/write/move/delete/admin/dotfiles).

> i’m not sure if directories inherit permissions from their parents right now, but maybe it could be made such that that is done?

yep! they do -- the only thing that stops permission inheritance is if you create another volume somewhere further down in the directory tree
