### ISSUE TITLE
Feature suggestion: Remember sort between page loads

### ISSUE THREAD

**Issue by icxes** [9001/copyparty#8]
I often sort by date. 
Currently I have to toggle it to sort by date every time I reload the page.
I think it would be cool if it was remembered between page loads.
Although if this is implemented, then some way to reset sorting would be necessary, too. (Well, I suppose it sorts by name by default, and you can just toggle that, but might not be obvious at first).

**Comment by 9001** [comment]
nice, good /r/ thx :+1:

should make initial page loads a bit snapper too actually

beta up at https://ocv.me/stuff/copyparty-sfx.py (probably new ver on sunday)
