### ISSUE TITLE
Wrong option description

### ISSUE THREAD

**Issue by hafeoz** [9001/copyparty#87]
**Describe the bug**
I've noticed following lines when scrolling through `copyparty -h` for leisure:
![图片](https://github.com/9001/copyparty/assets/95505675/9389b48c-d636-4f2d-beaa-75c4445733ac)

And the repeating `fy`/`fn` option doesn't make much sense to me. Is it supposed to be
```
[y]=crop, [n]=nocrop, [fy]=force-y, [fn]=force-n
```
instead?

**To Reproduce**
`copyparty -h`

**Expected behavior**
¯\\_(ツ)_/¯ I'm not a native English speaker, so maybe I'm wrong.

**Additional context**
The help text is in https://github.com/9001/copyparty/blob/hovudstraum/copyparty/__main__.py#L1213-L1214

**Comment by 9001** [comment]
yep you're absolutely right lol

thanks, must have messed up a copy/paste there :>
