### ISSUE TITLE
How to configure mimetype?

### ISSUE THREAD

**Issue by snapshotleisure** [9001/copyparty#89]
Hi, I saw somewhere in the release notes around being able to configure mimetypes, but i didnt see anything in the docs relating to how to configure it or with examples. Is it possible to give a simple config with how to configure the mimetypes?

Great application by the way!! copyparty is absolutely awesome!

Thanks

**Comment by 9001** [comment]
Thanks for the heads-up, I keep forgetting to document stuff :>

And thanks for using copyparty 😁 👍  glad you like it!

**Comment by snapshotleisure** [comment]
Thank you for the quick response! Awesome work as always!
