### ISSUE TITLE
requesting ?doc= of large files quickly exhausts memory

### ISSUE THREAD

**Issue by chinponya** [9001/copyparty#9]
Suppose we have a publicly accessible file in `/public/2GBfile.mkv`. Making a request to `http://localhost:3923/public/?doc=2GBfile.mkv` will cause the file to be fully loaded into memory, where it likely gets copied a few times, spiking the memory usage by about 5x the file size. This often leads to the OS' OOM-killer acting on the program, even on systems with a ton of available memory.

I'm not exactly sure what's the best mitigation to apply. Maybe the max file size permitted for `?doc=` should be limited (and configurable?) or maybe it should never be an option to begin with on binary files.

This issue shouldn't be specific to my setup, but just in case, here's what I have:
copyparty version 1.2.10 from pypi (the same thing happens on copyparty-sfx.py bundle), running under systemd
Python 3.9.6

direct python dependencies:
jinja2 3.0.2
mutagen 1.45.1
Pillow 0.3.2
pyopenssl 20.0.1
pyftpdlib 1.5.6

indirect python dependencies:
Babel 3.9.1
pytz 2021.3
markupsafe 2.0.1
olefile 0.46
defusedxml 0.7.1
packaging 20.9
pyparsing 2.4.7
six 1.16.0
pycparser 2.20
cffi 1.14.6
cryptography 3.4.8
pyasn 0.4.8
idna 3.2
pysendfile 2.0.1

other:
ffmpeg-full 4.4.1

config:
```
-i 0.0.0.0
-nc 10000
--http-only
--no-reload
--no-stack
--no-rescan
--no-robots
--no-dedup
--th-mt 8
u hotdog:hotdog
/srv/copyparty/public
/public
r
rwmd hotdog
c e2dsa
c e2ts
```

**Comment by 9001** [comment]
heh, good catch!

somebody had a cursed usecase for displaying binary files, but a size-limit definitely sounds good 👍

now anything bigger than `--txt-max` kB (default 64) won't get embedded, having the js fetch it as a file instead.

thx for partying 🎉

**Comment by chinponya** [comment]
You work fast. I can confirm that it works properly now. Thanks for fixing it.
Minor nitpick: now when I fat finger the `-txt-` link instead of the file name, there's no indication that anything is happening, let alone that I'm pulling a huge file in the background. At least now this doesn't crash the server, which is a good enough improvement for me, but maybe you are interested in making it better by showing a loading indicator or something.

**Comment by 9001** [comment]
Ah yeah good point, I'll add it to the next ver :+1: 
thx again!
