### ISSUE TITLE
Let users choose their password

### ISSUE THREAD

**Issue by aikooo7** [9001/copyparty#92]
**is your feature request related to a problem? Please describe.**
If you want to use this as "a friend asks for a account, I create it and he gets hes own folder" everything works expect that the friends needs to give you the password 

**Describe the idea / solution you'd like**
A button on the ui to let the usee change his password so you say "hey your password is bananas, when u log in change it". This could be enchanted using the password changing and maybe a flag "change password on login" where the user is required to change the password on login. I am taking my ideas from filebrowser as it was what I was using.

**Comment by 9001** [comment]
hey, thanks for trying copyparty!

and really cool idea, added :grin: :+1: 

there's a readme section which hopefully explains how it works: https://github.com/9001/copyparty#user-changeable-passwords

i'm planning to add one more big feature before the next release, maybe on sunday -- I've uploaded a beta with the user-changeable passwords here if you'd like to give it a try: https://ocv.me/copyparty/beta/copyparty-sfx.py

or if you're running copyparty in docker and can't wait until sunday, let me know which flavor you're using (ac/im/iv/dj) and I can build an image tomorrow :+1: 

PS: haven't tested if this actually works as intended with [password-hashing](https://github.com/9001/copyparty#password-hashing) yet, so probably best to save passwords in plaintext just for the beta

**Comment by aikooo7** [comment]
> hey, thanks for trying copyparty!
> 
> and really cool idea, added 😁 👍
> 
> there's a readme section which hopefully explains how it works: https://github.com/9001/copyparty#user-changeable-passwords
> 
> i'm planning to add one more big feature before the next release, maybe on sunday -- I've uploaded a beta with the user-changeable passwords here if you'd like to give it a try: https://ocv.me/copyparty/beta/copyparty-sfx.py
> 
> or if you're running copyparty in docker and can't wait until sunday, let me know which flavor you're using (ac/im/iv/dj) and I can build an image tomorrow 👍
> 
> PS: haven't tested if this actually works as intended with [password-hashing](https://github.com/9001/copyparty#password-hashing) yet, so probably best to save passwords in plaintext just for the beta

Hey, THANK YOU SO MUCH, this is really a better developed software than I was using before...

I can await until sunday for sure, but if you want me to test it in the meanwhile I am using the ac version.

When I saw the issue closed I judt thought you didnt want it, not that you already had done it.

Also since I am on the thanks part, you have a insane amount of documentation, and the first project that I could make read my ip from the cloudflare tunnel, and the project that made me be able to have hope and do it in my other container, as I had stopped becaude I tried tried tried and couldn't get it.

**Thank you**
